-- Fixed comparison query with proper window function usage
CREATE OR REPLACE TABLE GOLD_TABLE_COMPARISONS AS (
SELECT 
    GET_PRESIGNED_URL('@REQS_RESUMES',FILE_PATH) AS FILE_URL_CLICKABLE,
    JD.REQ_ID,
    JD.JOB_TITLE,
    JB.RESUME_ID,
    JB.VECTOR_EMBEDDING_VARIANT,
    JD.VECTOR_EMBEDDING_VARIANT_JOBREQ,
    JB.TECHNICAL_SKILLS as RESUME_TECH_SKILLS,
    JB.YEARS_OF_EXPERIENCE as RESUME_YOE,
    JD.TECHNICAL_SKILLS_REQUIRED as REQ_TECH_SKILLS,
    JD.YEARS_OF_EXPERIENCE_REQUIRED AS REQ_YOE,
    JB.MOST_RECENT_JOB_TITLE AS RESUME_CURRENT_JOB,
    JD.JOB_TITLE AS RESUME_JOB_TITLE,
    AI_SIMILARITY(TO_VARCHAR(JB.VECTOR_EMBEDDING_VARIANT),TO_VARCHAR(JD.VECTOR_EMBEDDING_VARIANT_JOBREQ),{'model': 'nv-embed-qa-4'}) as match_score,
    JB.FILE_PATH,
    JB.FILE_URL,
    JD.CATEGORY,  -- Fixed typo from CAETGORY and removed duplicate
    JB.COMMUNITY_VOLUNTEER_BOOL,
    JB.COMMUNITY_VOLUNTEER,
    JB.college_sports,
    JB.college_sports_division,
    JB.interesting,
    JB.personal_interests,
    JB.spoken_languages,
    -- Add ranking within each REQ_ID by match_score
    ROW_NUMBER() OVER (PARTITION BY JD.REQ_ID ORDER BY AI_SIMILARITY(TO_VARCHAR(JB.VECTOR_EMBEDDING_VARIANT),TO_VARCHAR(JD.VECTOR_EMBEDDING_VARIANT_JOBREQ),{'model': 'nv-embed-qa-4'}) DESC) as rank_within_req
FROM HACKATHON_2025.JOE.FLATTENED_RESUME_PDFS JB
INNER JOIN HACKATHON_2025.JOE.JOBREQ_FLATTENED JD
    ON JB.CATEGORY = JD.REQ_ID
ORDER BY JD.REQ_ID, match_score DESC
);

ALTER TABLE GOLD_TABLE_COMPARISONS ADD FIRSTNAME_LASTNAME VARCHAR;

SELECT * FROM GOLD_TABLE_COMPARISONS;

-- Alternative version if you want to filter to top N candidates per req:
-- Just add WHERE rank_within_req <= 5 (or whatever number you want)